trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: PowerShell@2
    displayName: "Run Terraform Plan Formatter"
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/terraform-plan-formatter/terraform-plan-formatter.ps1'
      arguments: '$(System.DefaultWorkingDirectory)/terraform-plan-formatter/tf3.log'

  - task: PowerShell@2
    displayName: "Run Terragrunt Plan Formatter"
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/terragrunt-plan-formatter/terragrunt-plan-formatter.ps1'
      arguments: '$(System.DefaultWorkingDirectory)/terragrunt-plan-formatter/tg1.log'
